# Generated by Django 4.2.2 on 2023-06-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gecko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genus', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('locale_subspecies', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('habitat', models.CharField(max_length=200)),
                ('snout_to_vent', models.CharField(max_length=200)),
                ('lifespan', models.CharField(max_length=200)),
                ('species_range', models.CharField(max_length=200)),
            ],
        ),
    ]
