# Generated by Django 4.2.2 on 2023-06-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geckos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gecko',
            name='discovered',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
